version: '3.7'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_PASSWORD=password
      - RABBITMQ_USERNAME=user
    volumes:
      - './data:/bitnami/rabbitmq/mnesia'
    networks:
      - messaging

networks:
  messaging:
    driver: bridge